CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),

	[Guid] UniqueIdentifier NOT NULL UNIQUE DEFAULT NEWID(),

	[CreatedAtDateTimeUTC] DateTime NOT NULL DEFAULT GETUTCDATE(),

	[LastUpdatedDateTimeUTC] DateTime NULL,

	[Email] NVARCHAR(MAX) NOT NULL,

	[AccountName] NVARCHAR(100) NOT NULL,

	[Name] NVARCHAR(100) NOT NULL
)
