CREATE TABLE [dbo].[Organization]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY (1, 1),

	[OwningUserId] INT NOT NULL REFERENCES [User](Id),
	
	[Guid] UNIQUEIDENTIFIER NOT NULL UNIQUE DEFAULT NEWID(),
	
	[Name] NVARCHAR(MAX) NOT NULL
)
